apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "VirtoCommerce-StoreFront.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "VirtoCommerce-StoreFront.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "VirtoCommerce-StoreFront.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "VirtoCommerce-StoreFront.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
          - name: config-volume
            mountPath: /opt/virtocommerce/storefront/appsettings.json
            subPath: appsettings.json
          - name: cms-content-volume
            mountPath: /opt/virtocommerce/storefront/wwwroot/cms-content

      volumes:
      - name: config-volume
        configMap:
          name: vc-storefront-appsettings
          items:
           - key: appsettings.json
             path: appsettings.json
      - name: cms-content-volume
        hostPath:
          path: /data/cms-content/
          type: DirectoryOrCreate
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
