apiVersion: v1
kind: Service
metadata:
  name: {{ include "VirtoCommerce-StoreFront.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "VirtoCommerce-StoreFront.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      name: http
      nodePort: {{ .Values.service.port }}
  selector:
    {{- include "VirtoCommerce-StoreFront.selectorLabels" . | nindent 4 }}
